server:
  port: 3000
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    username: prod
    password: password
    url: jdbc:postgresql://localhost:5431/product

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

