server:
  port: 3002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: order-service
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5431/order_service
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
  flyway:
    url: "jdbc:postgresql://localhost:5431/order_service"
    user: user
    password: password
  #    locations: classpath:db/migration
  cloud:
    function:
      definition: dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: ${spring.application.name}
          content-type: application/json
        acceptOrder-out-0:
          destination: order-accepted
          content-type: application/json
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9093

management:
  endpoints:
    web:
      exposure:
        include: refresh
client:
  product-service-uri: http://localhost:3000/api/v1
