server:
  port: 3006
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted
          content-type: application/json
        packlabel-out-0:
          destination: order-dispatched
          content-type: application/json
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9093